import SwiftUI

/// Apple Intelligence-generated 3–4 sentence summary of the user's stats.
/// Surfaces graceful fallback messages on machines without Foundation Models /
/// without Apple Intelligence enabled.
struct InsightCard: View {
    @Bindable var store: DataStore

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                CardHeader(
                    title: "AI summary",
                    symbol: "sparkles",
                    tint: Palette.brand,
                    info: "A 3–4 sentence summary generated by Apple Intelligence — fully on-device, no network call, no API key. Auto-refreshes every 30 minutes when the dashboard is open; tap the refresh icon for an immediate regeneration."
                )
                Spacer(minLength: 0)
                if store.insightLoading {
                    ProgressView().controlSize(.small)
                } else if case .ready = InsightGenerator.status {
                    Button {
                        Task { await store.regenerateInsight() }
                    } label: {
                        Image(systemName: "arrow.clockwise")
                            .imageScale(.small)
                    }
                    .buttonStyle(.borderless)
                    .help("Regenerate")
                }
            }

            content
                .frame(maxWidth: .infinity, alignment: .leading)

            if let updated = store.insightUpdatedAt, store.insight != nil {
                HStack {
                    Image(systemName: "applelogo")
                        .font(.system(size: 9))
                        .foregroundStyle(.tertiary)
                    Text("On-device · updated \(relativeTime(updated))")
                        .font(.system(size: 10))
                        .foregroundStyle(.tertiary)
                    Spacer(minLength: 0)
                }
            }
        }
        .healthCard()
    }

    @ViewBuilder
    private var content: some View {
        switch InsightGenerator.status {
        case .ready:
            if let insight = store.insight {
                Text(insight)
                    .font(.system(size: 13))
                    .foregroundStyle(.primary)
                    .lineSpacing(2)
                    .fixedSize(horizontal: false, vertical: true)
            } else if store.insightLoading {
                Text("Generating…")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            } else {
                Text("Tap the refresh icon for a quick AI-generated summary of your activity.")
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
            }
        case .requiresMacOS26:
            unavailableNote("AI insights require **macOS 26+** with Apple Intelligence. Your current macOS is older — the rest of ClaudeHealth works as normal.")
        case .requiresAppleIntelligence:
            unavailableNote("Enable Apple Intelligence in **System Settings → Apple Intelligence & Siri** to generate insights here. Nothing leaves your Mac.")
        case .modelDownloading:
            unavailableNote("Apple Intelligence model is downloading in the background. Try again in a few minutes.")
        case .unavailable(let reason):
            unavailableNote(reason)
        }
    }

    private func unavailableNote(_ markdown: String) -> Text {
        Text(.init(markdown))
            .font(.system(size: 12))
            .foregroundStyle(.secondary)
    }

    private func relativeTime(_ d: Date) -> String {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f.localizedString(for: d, relativeTo: Date())
    }
}
